import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import Header from "@/components/Header";
import I18nProvider from "@/libs/i18nProvider";
import StoreProvider from "@/store/StoreProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "SWD Frontend Test By Art",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${geistSans.className}`}>
        <AntdRegistry>
          <StoreProvider>
            <I18nProvider>
              <Header />
              {children}
            </I18nProvider>
          </StoreProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
